{% set name = "grpclib" %}
{% set version = "0.4.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grpclib-{{ version }}.tar.gz
  sha256: 2988ef57c02b22b7a2e8e961792c41ccf97efc2ace91ae7a5b0de03c363823c3

build:
  number: 0
  noarch: python
  entry_points:
    - protoc-gen-python_grpc=grpclib.plugin.main:main
    - protoc-gen-grpclib_python=grpclib.plugin.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - dataclasses
    - h2 <5,>=3.1.0
    - multidict
test:
  imports:
    - grpclib
    - grpclib.channelz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vmagamedov/grpclib
  summary: Pure-Python gRPC implementation for asyncio
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - asford
